[package]
name = "nara"
version = "0.1.0"
authors = ["vinhig <vincent.higginson@student.unamur.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.23"
gl = "0.14.0"
